# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff8641b7852e87830dbc312df7943ad1fb03e5abbad6dcb833eb8d777f3e0ec59ddd076174ef018ecfcf8ca791e4c486798ebbd0742fb39c626f8994d060aee4

test:
  secret_key_base: f5967c1d8c72fbb8df96feb6bb4a49aa1c5877938a10a36954522af164045a679991eda692263d17b00acfe31a1a8b8cf19c8d82b79c1482045dab40bd485a9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
